# Generated by Django 3.2.10 on 2022-08-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='statusy',
            field=models.CharField(choices=[('exists', 'Exists'), ('ordered', 'Ordered'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('confirmed', 'Confirmed')], max_length=25, null=True),
        ),
    ]
